news_list = [
    '''Alphabet’s $32 Billion Wiz Acquisition Signals a Cloud-Security Arms Race. Alphabet dropped a bombshell today, announcing its intent to scoop up cloud-security firm Wiz for a staggering $32 billion—the biggest deal in its history to bolster Google Cloud’s defenses. Sources say the move, first hinted at by X posts from @SINewsUpdates and @PiQSuite, is a direct shot at Microsoft and AWS in the escalating cloud wars. Wiz, founded by ex-Israeli military tech wizards, has been a darling of the cybersecurity scene, hitting a $12 billion valuation last year. Now, Alphabet’s betting big to plug gaps in its cloud armor as AI-driven threats spike. Insiders whisper the Federal Trade Commission might squint at this one, but with cyber breaches up 30% in 2025 per TechCrunch, Alphabet’s not waiting for permission. Expect snarky X threads about Google "buying its way to relevance" to light up tonight.''',
    
    '''Pune’s Icertis Nabs $50 Million to Keep SaaS Dreams Alive. Pune-based SaaS poster child Icertis is swimming in cash again, securing $50 million in fresh funding as of March 19, per YourStory’s daily roundup. The contract-management giant, already a unicorn, is riding the wave of enterprise digitization, with its AI-powered platform now managing over $1 trillion in contract value globally. This round, led by some hush-hush venture bigwigs, comes as Icertis eyes an IPO in 2026—because why not cash out while the market’s still pretending to love tech? X users are already joking about “Pune’s new overlords,” but with competitors like DocuSign lurking, this war chest might just keep Icertis’s servers humming through the next recession.''',
    
    '''Nvidia’s GTC 2025 Chip Drop: AI Overlords Rejoice. Nvidia’s GTC 2025 kicked off today with Jensen Huang unveiling next-gen chips that promise to turbocharge AI workloads, cementing its stranglehold on the market. Details are trickling out via X buzz and TechCrunch snippets, with the Blackwell architecture stealing the show—think 50% more juice for generative AI models. Priced for the deep-pocketed (we’re talking six figures per unit), these beasts are aimed at startups and tech titans desperate to out-AI each other. Posts on X are hailing it as “the endgame for CPU peasants,” while critics snark about Nvidia’s monopoly jacking up costs for scrappy founders. Either way, the AI hype train’s not slowing down.''',
    
    '''AWS Exec Jumps Ship to Start a Generative AI Venture. An AWS generative AI honcho bailed today to launch their own startup, per whispers in the tech ether and a nod from YourStory. After years of steering Amazon’s AI ship, this unnamed exec is betting on the generative AI gold rush—think ChatGPT rivals or deepfake factories. No word on funding yet, but X is abuzz with speculation about poached talent and Amazon’s inevitable revenge plot. With AWS still flexing its $100 billion cloud muscle, this defection’s a juicy middle finger to Jeff Bezos’s empire. Watch for this one to trend as the startup graveyard fills up with less lucky dreamers.''',
    
    '''Agentic AI’s AMT Scores Seed Cash, Wants to Be ‘AdWords for Influencers’. Agentic AI startup AMT nabbed a seed round today—amount undisclosed, but let’s assume it’s enough to buy a few Silicon Valley lattes. Per Indian Startup News, AMT’s pitching itself as the “Google AdWords for influencers,” using AI to match brands with TikTok wannabes and Instagram flexers. The idea’s got legs in a $20 billion creator economy, but X users are already dunking on it with “AI can’t fix cringe” jabs. Still, with ad tech ripe for disruption, AMT’s founders are banking on brands’ desperation to go viral. Expect this to trend as the hype builds—or flops.''',
    
    '''Dezerv’s $5.3 Million ESOP Buyback: Wealth-Tech’s Latest Flex. Wealth-tech startup Dezerv made waves today, wrapping up a $5.3 million ESOP buyback (Rs 46 crore) for its crew, per YourStory. The Mumbai-based firm, which helps India’s nouveau riche manage their piles of cash, is flaunting its growth—$100 million in assets under management and counting. X posts are split between “employee win” cheers and “rich get richer” eye-rolls. With India’s wealth-tech space heating up, Dezerv’s move screams confidence—or desperation to keep talent from jumping to the next shiny unicorn. Either way, it’s trending as startup perks hit peak absurdity.'''
]